### ISSUE TITLE
可以绕过二次认证提高网速吗？

### ISSUE THREAD

**Issue by JIANG3330** [liangjies/minieap-for-zqu#1]

**Comment by liangjies** [comment]
你可以设置DHCP 方式为“认证后DHCP”试一试

**Comment by JIANG3330** [comment]
@liangjies 选认证后依然会弹出天翼认证页面，无法提速。 
顺便问一下出现无法打开配置文件错误怎么解决呢？
[2019/11/30 20:14:05][E] 无法打开配置文件: No such file or directory (2)
[2019/11/30 20:14:05][W] 配置文件解析出错，请注意命令行参数是否完整

**Comment by liangjies** [comment]
@JIANG3330 “无法打开配置文件”，这个你可以忽略，也可以新建一个配置文件

**Comment by JIANG3330** [comment]
好的，谢谢你！

**Comment by Createcc** [comment]
那些，100Mbps，提高网速的，不是通过绕过二次验证的
↓下方为电信认证页URL的最后部分 最后的wlanuserip为dhcp获取到的ipv4地址
.99.27&wlanuserip=10.*.*.*
很容易可以看出，这是一个根据内网IP段限速的过程，要过限速，通过该Ip与本地IP不对应即可
内网是不限速的，可以分析得到，限速的不是锐捷（针对电信用户分析，移动另说）
